"""
SQLAlchemy ORM models — canonical schema shared between backend and agent.

Tables
------
* ``trades``        – Trade proposals with full lifecycle and LLM output
* ``analysis_logs`` – Per-analysis audit trail with pipeline step tracking
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime, timezone

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


# ── Enums ──────────────────────────────────────────────────────────────────

class TradeStatus(str, enum.Enum):
    """Trade lifecycle states."""

    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


# ── Timestamp mixin ────────────────────────────────────────────────────────

class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


# ── Trade ──────────────────────────────────────────────────────────────────

class Trade(Base, TimestampMixin):
    """Trade proposal generated by the AI analysis pipeline."""

    __tablename__ = "trades"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    ticker: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        index=True,
    )
    strategy: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        default="momentum_dip",
    )
    # LLM output
    decision: Mapped[str | None] = mapped_column(
        String(16),
        nullable=True,
        comment="BUY | NO_TRADE from LLM analysis",
    )
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    reasoning: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="LLM reasoning text",
    )
    # Entry parameters
    proposed_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    position_size: Mapped[float | None] = mapped_column(Float, nullable=True)
    position_size_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    exit_condition: Mapped[str | None] = mapped_column(Text, nullable=True)
    stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    take_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_reward_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Lifecycle
    status: Mapped[TradeStatus] = mapped_column(
        Enum(TradeStatus, name="trade_status_enum", create_constraint=True),
        nullable=False,
        default=TradeStatus.PENDING,
        index=True,
    )
    # Technical indicators at decision time
    rsi_2_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    chop_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    sma_200_value: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Metadata
    sector: Mapped[str | None] = mapped_column(String(50), nullable=True)
    human_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationship
    analysis_logs: Mapped[list[AnalysisLog]] = relationship(
        "AnalysisLog",
        back_populates="trade",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="AnalysisLog.created_at",
    )

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "ticker": self.ticker,
            "strategy": self.strategy,
            "decision": self.decision,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "proposed_price": self.proposed_price,
            "position_size": self.position_size,
            "position_size_pct": self.position_size_pct,
            "exit_condition": self.exit_condition,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward_ratio": self.risk_reward_ratio,
            "status": self.status.value,
            "rsi_2_value": self.rsi_2_value,
            "chop_value": self.chop_value,
            "sma_200_value": self.sma_200_value,
            "sector": self.sector,
            "human_feedback": self.human_feedback,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self) -> str:
        return f"<Trade {self.ticker} {self.status.value}>"


# ── AnalysisLog ────────────────────────────────────────────────────────────

class AnalysisLog(Base, TimestampMixin):
    """Per-analysis audit log with pipeline step tracking and LLM output."""

    __tablename__ = "analysis_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    trade_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("trades.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="NULL for dead-letter entries not associated with a trade",
    )
    ticker: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        index=True,
    )
    # Pipeline progress
    step1_passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    step2_passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    step3_passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # Indicator snapshots
    rsi2: Mapped[float | None] = mapped_column(Float, nullable=True)
    chop: Mapped[float | None] = mapped_column(Float, nullable=True)
    sma200: Mapped[float | None] = mapped_column(Float, nullable=True)
    price: Mapped[float | None] = mapped_column(Float, nullable=True)
    # LLM output
    raw_llm_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    technical_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    news_context: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    llm_decision: Mapped[str | None] = mapped_column(String(16), nullable=True)
    llm_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Error / retry tracking
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    dead_letter: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Relationship
    trade: Mapped[Trade | None] = relationship("Trade", back_populates="analysis_logs")

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "trade_id": str(self.trade_id) if self.trade_id else None,
            "ticker": self.ticker,
            "step1_passed": self.step1_passed,
            "step2_passed": self.step2_passed,
            "step3_passed": self.step3_passed,
            "rsi2": self.rsi2,
            "chop": self.chop,
            "sma200": self.sma200,
            "price": self.price,
            "raw_llm_reasoning": self.raw_llm_reasoning,
            "technical_data": self.technical_data,
            "news_context": self.news_context,
            "llm_decision": self.llm_decision,
            "llm_confidence": self.llm_confidence,
            "error_message": self.error_message,
            "retry_count": self.retry_count,
            "dead_letter": self.dead_letter,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

    def __repr__(self) -> str:
        return f"<AnalysisLog {self.ticker} steps={self.step1_passed}/{self.step2_passed}/{self.step3_passed}>"


# ── FundamentalSnapshot ───────────────────────────────────────────────────

class FundamentalHealth(str, enum.Enum):
    """Fundamental health classification."""
    HEALTHY = "HEALTHY"
    CAUTION = "CAUTION"
    HIGH_RISK = "HIGH_RISK"


class FundamentalSnapshot(Base, TimestampMixin):
    """Per-ticker fundamental health snapshot, refreshed periodically.

    Persisted so any pipeline can query the latest health assessment
    without re-fetching from external APIs.
    """

    __tablename__ = "fundamental_snapshots"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    ticker: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        index=True,
    )
    as_of_date: Mapped[date] = mapped_column(
        Date,
        nullable=False,
        comment="Date the fundamental data was fetched",
    )
    # Health scoring (0–5)
    health_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="0=all red flags, 5=all metrics healthy",
    )
    health_label: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        default="CAUTION",
    )
    # Key metrics (null = unavailable)
    market_cap: Mapped[float | None] = mapped_column(Float, nullable=True)
    trailing_pe: Mapped[float | None] = mapped_column(Float, nullable=True)
    forward_pe: Mapped[float | None] = mapped_column(Float, nullable=True)
    debt_to_equity: Mapped[float | None] = mapped_column(Float, nullable=True)
    current_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    return_on_equity: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_margins: Mapped[float | None] = mapped_column(Float, nullable=True)
    revenue_growth: Mapped[float | None] = mapped_column(Float, nullable=True)
    beta: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Detail
    flags: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    raw_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": str(self.id),
            "ticker": self.ticker,
            "as_of_date": self.as_of_date.isoformat() if self.as_of_date else None,
            "health_score": self.health_score,
            "health_label": self.health_label,
            "market_cap": self.market_cap,
            "trailing_pe": self.trailing_pe,
            "forward_pe": self.forward_pe,
            "debt_to_equity": self.debt_to_equity,
            "current_ratio": self.current_ratio,
            "return_on_equity": self.return_on_equity,
            "profit_margins": self.profit_margins,
            "revenue_growth": self.revenue_growth,
            "beta": self.beta,
            "flags": self.flags,
            "raw_data": self.raw_data,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return f"<FundamentalSnapshot {self.ticker} {self.health_label} score={self.health_score}>"